### ISSUE TITLE
Play again issue

### ISSUE THREAD

**Issue by rohit-373** [SoulNinja-dev/tictactoe_Flutter#12]

**Comment by rohit-373** [comment]
Hey there, I have used your app and it is excellent !! 👍
After a game ends, you have made the app to go to another window and ask the user to play again.
But I went back instead of clicking play again. Then I found out there was no button to play again. (See the screenshot)
So you should probably add a "play again" within the same window so that we can avoid that weird type of issue
Anyways congratulations on your first app in google play store 👍


// Rohit

_Nothing is perfect_

![Screenshot_20210516-141133.png](https://user-images.githubusercontent.com/48488024/118391682-3b65cc00-b653-11eb-9eaa-c96cb2efbb0d.png)

**Comment by aadtyn** [comment]
new release has fixed this bug
