### ISSUE TITLE
Problem of pressing multiple squares.

### ISSUE THREAD

**Issue by kairussboi** [SoulNinja-dev/tictactoe_Flutter#8]
If you press multiple squares in one turn, all get changed to X. So if you press 3 squares you can easily win.Kindly fix this bug

**Comment by kairussboi** [comment]
I mean all get changed to X

**Comment by aadtyn** [comment]
Yes, just noticed it.
this can be fixed by adding a delay when the bot plays and also having a check that play is called only once per chance.

**Comment by kairussboi** [comment]
The problem still persists in the new release. Kindly fix the issue as soon
as possible. Btw half these words were recommended by Google lol 😂

**Comment by aadtyn** [comment]
Yep, not yet fixed. I am working on pushing this app to google play store so that the updates will be easier. once that is done I will work on these bugs 👍
![image](https://user-images.githubusercontent.com/68557696/117567104-17950a00-b0d8-11eb-89ec-d5decec39848.png)

**Comment by aadtyn** [comment]
fixed in latest commit
